"""Loader for RULER-NIAH jsonl data (generated by scripts/prepare_niah_data.sh).

Layout: ``<data_root>/<seq_len>/<task>/validation.jsonl``. Each record is the
RULER-fork schema::

    {
      "index": int,                  # answer char offset (fork detail; unused)
      "input": str,                  # task text WITHOUT the answer prefix
      "outputs": [str, ...],         # gold needle values (string-match refs)
      "length": int,                 # generator token length incl. gen budget
      "answer_prefix": str,          # assistant-side prefix, e.g. " The special magic number ... is"
      "token_position_answer": int,  # needle token depth (for depth heatmaps)
    }
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

REQUIRED_FIELDS = ("input", "outputs", "answer_prefix")

NIAH_TASKS = (
    "niah_single_1",
    "niah_single_2",
    "niah_single_3",
    "niah_multikey_1",
    "niah_multikey_2",
    "niah_multikey_3",
    "niah_multivalue",
    "niah_multiquery",
)


def default_niah_data_root() -> Path:
    env_root = os.environ.get("NIAH_DATA_ROOT")
    if env_root:
        return Path(env_root).expanduser()
    return Path.home() / "data" / "ruler_niah" / "llama3"


def resolve_niah_file(
    task: str,
    seq_len: int,
    data_root: str | os.PathLike[str] | None = None,
) -> Path:
    root = Path(data_root).expanduser() if data_root else default_niah_data_root()
    return root / str(int(seq_len)) / task / "validation.jsonl"


def load_niah_records(
    task: str,
    seq_len: int,
    data_root: str | os.PathLike[str] | None = None,
) -> list[dict[str, Any]]:
    path = resolve_niah_file(task, seq_len, data_root)
    if not path.is_file():
        raise FileNotFoundError(
            f"NIAH data file not found: {path}. Generate it with "
            "scripts/prepare_niah_data.sh (set NIAH_DATA_ROOT / --data-root)."
        )
    records: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as handle:
        for line_no, line in enumerate(handle):
            if not line.strip():
                continue
            record = json.loads(line)
            missing = [f for f in REQUIRED_FIELDS if f not in record]
            if missing:
                raise ValueError(
                    f"{path}:{line_no + 1} is missing required fields {missing}; "
                    "regenerate the data with the current RULER fork "
                    "(needs answer_prefix support)"
                )
            if not isinstance(record["outputs"], list) or not record["outputs"]:
                raise ValueError(f"{path}:{line_no + 1} has empty outputs")
            records.append(record)
    if not records:
        raise ValueError(f"NIAH data file is empty: {path}")
    return records
